version: 0.2
eb_codebuild_settings:
  CodeBuildServiceRole: aws_code_build
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/standard:5.0
  Timeout: 30

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
      - echo INSTALL completed on `date`
  build:
    commands:
      - echo BUILD started on `date`
      - echo `pwd`
      - npm run build
      - echo BUILD completed on `date`
artifacts:
  files:
    - package.json
    - dist/**/*

cache:
  paths:
    - '/node_modules/*/**'